mainline/config/routes.rb
# encoding: utf-8
#--
#   Copyright (C) 2012-2014 Gitorious AS
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU Affero General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU Affero General Public License for more details.
#
#   You should have received a copy of the GNU Affero General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.
#++

Gitorious::Application.routes.draw do
  ### R0. Site index
  root :to => "site#index"

  get "/gitlab-import" => "gitlab_import#new"

  ### R1. Repository browser (instance is configured in an initializer)
  match "/:project_id/:repository_id/:action/*slug" => Gitorious::RepositoryBrowser.instance, :action => /(source|tree_history|raw|blame|history|archive)/, :as => :repository_browser
  match "/:project_id/:repository_id/refs" => Gitorious::RepositoryBrowser.instance, :as => :repository_refs

  ### R2. User routes
  resources :users, :only => [:new, :create] do
    collection do
      get "/forgot_password" => "password_resets#new", :as => :forgot_password
      post "/forgot_password" => "password_resets#generate_token", :as => :forgot_password_create
      get "/reset_password/:token" => "password_resets#prepare_reset", :as => :reset_password
      put "/reset_password/:token" => "password_resets#reset", :as => :do_reset_password
      get "/activate/:activation_code" => "user_activations#create"
      get "/pending_activation" => "user_activations#show", :as => :pending_activation
      get "/openid_build" => "open_id_users#new"
      post "/openid_create" => "open_id_users#create"
      get "/new" => "users#new"
      get "/view_state/repository/:id.:format" => "repository_view_state#show", :as => :repository_view_state
      get "/view_state/project/:id.:format" => "project_view_state#show", :as => :project_view_state
      get "/view_state.:format" => "user_view_state#show", :as => :view_state

      # Used to be we supported things like /users/~zmalltalker/mainline
      # No more, ~<user_name> is the canonical user URL namespace
      get "/*slug" => (redirect do |params, request|
                         request.fullpath.sub("users/", "~")
                       end), :slug => /.*/
    end
  end

  # `resources :users` can't do the ~<user> ids
  get "/~:id.keys" => "public_keys#index", :id => /[^\/]+/
  get "/~:id(.:format)" => "users#show", :as => "user", :id => /[^\/]+/
  get "/~:id/edit(.:format)" => "users#edit", :as => "edit_user", :id => /[^\/]+/
  put "/~:id(.:format)" => "users#update", :id => /[^\/]+/
  delete "/~:id(.:format)" => "users#destroy", :id => /[^\/]+/

  # Additional user actions
  scope "/~:id", :id => /[^\/]+/, :as => :user do
    get "/delete_current" => "users#destroy", :as => :delete_current
    delete "/avatar" => "avatars#destroy"
    get "/watchlist" => "user_watchlists#show", :as => :watchlist
    get "/feed" => "user_feeds#show", :as => :feed
    put "/update_password" => "passwords#update", :as => :update_password

    get "/aliases" => "users#edit", :defaults => { :tab => "email-aliases" }, :as => :edit_email_aliases
    get "/ssh-keys" => "users#edit", :defaults => { :tab => "ssh-keys" }, :as => :edit_ssh_keys
    get "/password" => "users#edit", :defaults => { :tab => "change-password" }, :as => :edit_password
    get "/favorites" => "users#edit", :defaults => { :tab => "manage-favorites" }, :as => :edit_favorites
  end

  # Nested user resources. This is in a separate scope because the
  # controllers expect params[:user_id] to contain the user, not
  # params[:id] as in the scope above
  scope "/~:user_id", :user_id => /[^\/]+/, :as => :user do
    resources :keys, :only => [:new, :create, :destroy, :index]

    resources :aliases do
      member do
        get :confirm
      end
    end

    get "/repositories" => "repositories#index"
    resource :license, :only => [:show, :edit, :update]
    match "/*slug" => "owner_redirections#show"
  end

  ### R3. Sessions
  resource :sessions
  get "/sessions" => "sessions#create", :as => :open_id_complete
  get "/login" => "sessions#new", :as => :login
  get "/login/http" => "sessions#http" # for Kerberos authentication
  get "/logout" => "sessions#destroy", :as => :logout

  ### R4. Groups
  resources :groups, :only => [:index, :new, :create]
  # `resource :groups` can't do the +<group> ids
  get "/+:id(.:format)" => "groups#show", :as => "group", :id => /[^\/]+/
  get "/+:id/edit(.:format)" => "groups#edit", :as => "edit_group", :id => /[^\/]+/
  put "/+:id(.:format)" => "groups#update", :id => /[^\/]+/
  delete "/+:id(.:format)" => "groups#destroy", :id => /[^\/]+/

  # Additional group actions
  scope "/+:id", :id => /[^\/]+/, :as => :group do
    delete "avatar" => "groups#avatar"
  end

  # Nested group resources. This is in a separate scope because the
  # controllers expect params[:group_id] to contain the group, not
  # params[:id] as in the scope above
  scope "/+:group_id", :id => /[^\/]+/, :as => :group do
    resources :memberships
    get "/repositories" => "repositories#index"
    match "/*slug" => "owner_redirections#show"
  end

  ### R5. Site-wide wiki
  get "/wiki/:site_id/config" => "site_wiki_pages#repository_config", :as => :site_wiki_git_access_connect
  get "/wiki/:site_id/writable_by" => "site_wiki_pages#writable_by", :as => :site_wiki_git_writable_by

  resources :site_wiki_pages, :path => "/wiki" do
    collection do
      get :git_access
    end

    member do
      get :history
    end
  end

  ### R6. Direct merge request access
  match "/merge_request_landing_page" => "merge_requests#oauth_return", :as => :merge_request_landing_page
  get "/merge_requests/:id" => "merge_requests#direct_access", :as => :merge_request_direct_access

  ### R7. Site controller, various loose pages
  get "/activities" => "site#public_timeline", :as => :activity
  get "/dashboard" => "site#dashboard", :as => :dashboard
  get "/my-activities" => "site#my_activities", :as => :dashboard_my_activities
  get "/about" => "site#about", :as => :about
  get "/about/:action" => "site#index", :as => :about_page
  get "/contact" => "site#contact", :as => :contact

  ### R8. Administration
  namespace :admin do
    get "/" => redirect { |params, request| "/admin/repositories" }

    resources :users, :only => [:index, :new, :create] do
      member do
        put :suspend
        put :flip_admin_status
        put :unsuspend
        put :reset_password
      end

      resources :keys, only: [:index, :new, :create, :destroy]
    end

    resources :projects, :only => [:show] do
      resource :oauth_settings, :only => [:show, :edit, :update]
    end

    resources :repositories, :only => [:index] do
      member do
        put :recreate
      end
    end

    resources :project_proposals, :only => [:index, :new, :create]
    post "/project_proposals/:id/reject" => "project_proposals#reject"
    post "/project_proposals/:id/approve" => "project_proposals#approve"
  end

  ### R9. API
  namespace :api do
    get ":project_id/:repository_id/log/graph(.:format)" => "graphs#show"
    get ":project_id/:repository_id/log/graph/*branch(.:format)" => "graphs#show"

    namespace :internal do
      get "/repo-config", to: "repository_configurations#show"
      get "/authenticate", to: "users#authenticate"
      get "/hooks/pre-receive", to: "hooks#pre_receive"
      post "/hooks/post-receive", to: "hooks#post_receive"
    end
  end

  ### R10. Events
  resources :events do
    member do
      get :commits
    end
  end

  ### R11. Additional logged in user resources
  resources :messages do
    collection do
      get :sent
      put :bulk_update
      get :all
      get :auto_complete_for_message_recipients
    end

    member do
      post :reply
      put :read
    end
  end

  resources :favorites, :only => [:index, :create, :update, :destroy]

  ### R12. Search
  get "/search", :controller => "searches", :action => "show", :as => :search

  ### R13. Auto-completion
  resources :user_auto_completions, :only => [:index]
  resources :group_auto_completions, :only => [:index]

  ### R14. Projects
  resources :projects, :only => [:index, :create]
  get "/:id/edit(.:format)" => "projects#edit"

  resources :projects, :path => "/" do
    member do
      put :preview
      get :edit_slug
      put :edit_slug
      get :confirm_delete
      get "/ownership/edit" => "project_ownerships#edit", :as => :transfer_ownership
      put "/ownership/edit" => "project_ownerships#update", :as => :transfer_ownership
    end

    resources :project_memberships, :only => [:index, :new, :create, :destroy]
    get "/community", :controller => :project_community, :action => :index
    get "/merge_requests", :controller => :project_merge_requests, :action => :index

    resources :pages do
      collection do
        get :git_access
      end

      member do
        get :history
      end
    end

    ### R14.2. Repositories

    # Listing repositories and creating new ones happens over
    # /<project>/repositories/, e.g:
    #   /gitorious/repositories/new
    resources :repositories, :only => [:index, :new, :create]

    # Browsing, editing and destroying existing repositories happens over
    # /<project>/<repository_name>/, e.g.:
    #   /gitorious/mainline
    #   /gitorious/mainline/edit
    resources(:repositories, {
                :path => "/",
                :only => [:show, :edit, :update, :destroy]
              }) do
      member do
        post "/create_clone" => "repository_clones#create"
        get "/clone" => "repository_clones#new"
        get "/search_clones" => "repository_clone_searches#show"

mainline/app/helpers/merge_requests_helper.rb
# encoding: utf-8
#--
#   Copyright (C) 2012 Gitorious AS
#   Copyright (C) 2009 Nokia Corporation and/or its subsidiary(-ies)
#   Copyright (C) 2008 Johan Sørensen <johan@johansorensen.com>
#   Copyright (C) 2008 Tor Arne Vestbø <tavestbo@trolltech.com>
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU Affero General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU Affero General Public License for more details.
#
#   You should have received a copy of the GNU Affero General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.
#++

module MergeRequestsHelper
  include MergeRequestVersionsHelper
  include CommentsHelper

  def render_status_tag_list(statuses, target, active = nil)
    out = "<ul class=\"nav nav-tabs\">"

    if active.nil?
      out << "<li class=\"active\"><a>All</a></li>"
    else
      url = merge_request_link(target)
      out << "<li><a href=\"#{url}\">All</li>"
    end

    statuses.each do |status|
      if active == status.name
        out << "<li class=\"active\"><a>#{status.name}</a></li>"
      else
        out << "<li>#{link_to_status(target, status.name)}</li>"
      end
    end
    out << "</ul>"
    out.html_safe
  end

  def link_to_status(target, status)
    if params[:status].blank? && status == "open"
      link_to_selected_status(target, status)
    elsif params[:status] == status
      link_to_selected_status(target, status)
    else
      link_to_not_selected_status(target, status)
    end
  end

  def link_to_not_selected_status(target, status)
    link_to(h(status.to_s), merge_request_link(target, status))
  end

  def link_to_selected_status(target, status)
    url = merge_request_link(target, status)
    link_to(h(status.to_s), url, :class => "selected")
  end

  def merge_base_link(version)
    version.merge_base_sha[0..6]
  end

  # a href="#commit_<sha>" id="commit_<sha>" data-commit-sha="sha"
  def inline_commit_link(commit)
    inline_sha_link(commit.id_abbrev, commit.id)
  end

  def inline_sha_link(label, sha)
    content_tag(:a, label, {
        "data-commit-sha" => sha,
        :class => "clickable_commit",
        :href => "#"
      })
  end

  def colorized_status(status_tag)
    return "" unless status_tag
    (%Q{<span class="badge" style="background-color:#{h(status_tag.color)}">} +
     h(status_tag.name) + "</span>").html_safe
  end

  # By some arbitarily random standard, does this +version+ contain many commits?
  def many_commits?(version)
    version.affected_commits.length > 7
  end

  # TODO: Add a button to display the status. git cherry takes way too long for us to wait
  # for it to perform
  def commit_css_class(merge_request, commit)
    "unmerged"
  end

  def summarize_version(version)
    if version.affected_commits.blank?
      [
       summarize_version_with_single_sha(version.short_merge_base),
       summarize_version_with_several_shas("","")
      ].join("\n").html_safe
    else
      [
       summarize_version_with_single_sha(""),
       summarize_version_with_several_shas(version.short_merge_base,version.affected_commits.last.id_abbrev)
      ].join("\n").html_safe
    end
  end

  def summarize_version_with_single_sha(sha)
    options = {:class => "single_sha"}
    options[:style] = "display: none" if sha.blank?
    content_html = content_tag(:span, 'Showing', :class => 'label') + " " +
      content_tag(:code, sha, :class => 'merge_base')
    content_tag(:div, content_html, options)
  end

  def summarize_version_with_several_shas(first,last)
    options = {:class => "several_shas"}
    options[:style] = "display:none" if last.blank?
    content_html = content_tag(:span, 'Showing', :class => 'label') + " " +
      content_tag(:code, first, :class => 'first') + "-" +
      content_tag(:code, last, :class => 'last')
    content_tag(:div, content_html, options)
  end

  def status_open?(name)
    @statuses ||= {}
    return @statuses[name] if @statuses.key?(name)
    @statuses[name] = MergeRequestStatus.open?(name)
  end

  def version_drop_down(mr, current)
    choices = mr.versions.reverse.select { |v| v != current }.map do |v|
      path = project_repository_merge_request_version_path(mr.project, mr.target_repository, mr, :version => v.version)
      "<li><a href=\"#{path}\">Version #{v.version}</a></li>"
    end

    <<-HTML
      <li class="pull-right dropdown">
        <a href="#" class="dropdown-toggle">Version #{current.version}</a>
        <ul class="dropdown-menu">
          #{choices.join("")}
        </ul>
      </li>
    HTML
  end

  private

  def merge_request_link(target, status = nil)
    args = {}
    args[:status] = status if !status.nil?
    if target.is_a?(Repository)
      return project_repository_merge_requests_path(
        target.project,
        target,
        args)
    end

    project_merge_requests_path(target, args)
  end
end

mainline/app/views/merge_requests/show/_commits.html.erb
<%
#--
#   Copyright (C) 2012-2013 Gitorious AS
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU Affero General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU Affero General Public License for more details.
#
#   You should have received a copy of the GNU Affero General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.
#++
%>
<table class="table gts-mr-commit-table">
  <colgroup>
    <col class="sha-col"/>
    <col class="commit-msg-col"/>
    <col class="commit-date-col"/>
  </colgroup>
  <% commits.map { |commit| CommitPresenter.new(repository, commit) }.each do |commit| %>
    <tr>
      <td>
        <%= link_to(commit.short_oid, project_repository_commit_path(repository.project, repository, commit.id)) %>
      </td>
      <td>
        <%= commit.short_message %>
      </td>
      <td title="<%= commit.committed_date.utc %>">
        <%= time_ago_in_words(commit.committed_date) %> ago
      </td>
    </tr>
  <% end %>
</table>

mainline/app/views/merge_requests/show/_help.html.erb
<%
#--
#   Copyright (C) 2012-2014 Gitorious AS
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU Affero General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU Affero General Public License for more details.
#
#   You should have received a copy of the GNU Affero General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.
#++
%>
<div class="gts-mr-help-link clearfix">
  <a href="#mr-help" data-toggle="modal" class="pull-right">Help</a>
</div>
<%= modal_box 'Merge Request Help', 'mr-help' do %>
  <div class="gts-mr-help">
    <div class="gts-mr-help-content">
      <h4>How to update the merge request?</h4>
      <p>
        To update your merge request, either <%= link_to("edit here", :action =>
                                                   :edit) %> or push your changes through git. A new version of your merge
        request will be created, up until the last commit you push. You may make as
        many updates as you like; the last one will always be displayed by default
      </p>
      <pre><%= "git push #{merge_request.target_repository.push_url} #{merge_request.source_branch}:#{merge_request.ref_name}" -%></pre>
      <h4>How to merge these changes?</h4>
      <p>
        Pull the changes into a local branch for review, verify the changes (run
        tests etc) and then merge into master:
      </p>
      <pre># Check out a new branch for integration
git checkout -b merge-requests/<%= merge_request.sequence_number %>

# Fetch the merge request into this branch
git pull <%= merge_request.target_repository.default_clone_url %> <%= merge_request.ref_name %>

# Review commits
git log --pretty=oneline --abbrev-commit <%= merge_request.target_branch %>..merge-requests/<%= merge_request.sequence_number %>

# Apply the changes to your branch:
git checkout <%= merge_request.target_branch %>
git merge merge-requests/<%= merge_request.sequence_number %>
git push origin <%= merge_request.target_branch %></pre>
    </div>
  </div>
<% end %>

mainline/app/views/merge_requests/show/_options.html.erb
<%
  # encoding: utf-8
  #--
  #   Copyright (C) 2013 Gitorious AS
  #
  #   This program is free software: you can redistribute it and/or modify
  #   it under the terms of the GNU Affero General Public License as published by
  #   the Free Software Foundation, either version 3 of the License, or
  #   (at your option) any later version.
  #
  #   This program is distributed in the hope that it will be useful,
  #   but WITHOUT ANY WARRANTY; without even the implied warranty of
  #   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  #   GNU Affero General Public License for more details.
  #
  #   You should have received a copy of the GNU Affero General Public License
  #   along with this program.  If not, see <http://www.gnu.org/licenses/>.
  #++
  %>
<div class="options">
  <div class="btn-group">
    <% if merge_request.user == current_user %>
      <%= link_to t('views.common.edit'),
        [:edit, merge_request.source_repository.project, merge_request.target_repository, merge_request],
        :class => 'btn' %>
      <%= link_to t('views.common.delete'),
        [merge_request.source_repository.project, merge_request.target_repository, merge_request],
        :method => :delete,
        :data => { :confirm => 'Are you sure you want to delete this merge request?' },
        :class => 'btn' %>
    <% end %>
    <%= favorite_button(merge_request) %>
  </div>
</div>

mainline/app/views/merge_requests/show/_status.html.erb
<%
#--
#   Copyright (C) 2012-2013 Gitorious AS
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU Affero General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU Affero General Public License for more details.
#
#   You should have received a copy of the GNU Affero General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.
#++
%>
<%
  source_repo_link = project_repository_path(source_repo.project, source_repo)
  target_repo_link = project_repository_path(target_repo.project, target_repo)
  source_branch_link = project_repository_commits_in_ref_path(source_repo.project, source_repo, merge_request.source_branch)
  target_branch_link = project_repository_commits_in_ref_path(target_repo.project, target_repo, merge_request.target_branch)
%>

<div class="well gts-mr-status">
  <%= merge_request.status_label_tag %>
  <div class="gts-mr-status-desc">
    <%= link_to(avatar(user, :size => 24) + " #{user.login}", user_path(user)) %>
    requested a merge from
    <%= link_to(source_repo.name, source_repo_link) %>:<%= link_to(merge_request.source_branch, source_branch_link) %>
    to <%= link_to(target_repo.name, target_repo_link) %>:<%= link_to(merge_request.target_branch, target_branch_link) %>
    <%= time_ago_in_words(merge_request.created_at) %> ago
  </div>
</div>